GET http://localhost:3000/sensors/my-sensors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImF5c2UuYmFsQGV4YW1wbGUuY29tIiwiZnVsbE5hbWUiOiJBecWfZSBCYWwiLCJpYXQiOjE3NDcxNDk2NzQsImV4cCI6MTc0NzE1MzI3NH0.Vn1i7WsFkjjcufjjNvVr4ovLcBdZEAsTIb3CbPhzHdg