GET http://localhost:3000/sensors/SENS2001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJmdWxsTmFtZSI6IlRlc3QgS3VsbGFuxLFjxLEiLCJpYXQiOjE3NDY2MzA4NDMsImV4cCI6MTc0NjYzNDQ0M30.v9zWpaA1GZp2HEGBmi36celKrpPze8dnaaemSRMbekE